export interface Artwork {
  id: number;
  title: string;
  description: string;
  image: string;
  metadata: string;
}

export const artworks: Artwork[] = [
  {
    id: 1,
    title: "Relaxing by the Volcano",
    description: "A cartoon character lounges on a pink float in a pool, wearing VR goggles and holding a smoking device labeled 'caldera.' In the background, a volcano erupts with smoke and lava, while birds fly across a vibrant sunset sky.",
    image: "https://ext.same-assets.com/1262238375/342162195.jpeg",
    metadata: "Metadata Generated by GPT-4o"
  },
  {
    id: 2,
    title: "Cartoon Construction Worker Duck",
    description: "A cartoon duck dressed as a construction worker, wearing a yellow hard hat and holding a blueprint labeled 'Built Different'. The background features a chain-link fence and a city skyline at sunset, with a hexagonal logo on the right.",
    image: "https://ext.same-assets.com/2885455740/849522504.jpeg",
    metadata: "Metadata Generated by GPT-4o"
  },
  {
    id: 3,
    title: "Scientist Fish in Lab",
    description: "A cartoon fish character dressed as a scientist is in a laboratory setting. The fish is wearing a white lab coat, red tie, and large protective goggles. It is holding a test tube with a red liquid in one hand and pointing to a clipboard with the other. A microscope is on the table, and there are additional test tubes in a rack. The background features a simple wall with a geometric artwork.",
    image: "https://ext.same-assets.com/3232376289/849522504.jpeg",
    metadata: "Metadata Generated by GPT-4o"
  },
  {
    id: 4,
    title: "Skydiving Frog with Ethereum Gem",
    description: "A cartoon frog character in a pilot outfit is skydiving above the clouds, holding a gem with the Ethereum logo. The frog is wearing goggles and a backpack, and is joyfully riding on a small airplane labeled 'caldera'.",
    image: "https://ext.same-assets.com/3497615646/849522504.jpeg",
    metadata: "Metadata Generated by GPT-4o"
  },
  {
    id: 5,
    title: "Animated Character in Cinema",
    description: "An animated character with a pumpkin-like head, wearing a suit and hat, is sitting in a cinema eating popcorn. The character has a mischievous expression and is surrounded by red theater seats. A 'caldera' logo is visible on the wall.",
    image: "https://ext.same-assets.com/2133133384/849522504.jpeg",
    metadata: "Metadata Generated by GPT-4o"
  },
  {
    id: 6,
    title: "Disco Frog",
    description: "A cartoon frog character dressed in a white disco suit with a purple shirt and sunglasses, dancing energetically in a vibrant disco setting with colorful lights and a cheering crowd.",
    image: "https://ext.same-assets.com/635159331/849522504.jpeg",
    metadata: "Metadata Generated by GPT-4o"
  },
  {
    id: 7,
    title: "Cartoon Characters with Smiling Faces",
    description: "A cartoon image featuring three characters with exaggerated smiling faces and large eyes. The character on the left has long red hair and wears a black top with 'caldera' written on it. The middle character, wearing a blue shirt labeled 'DEVELOPER,' looks back over their shoulder. The character on the right has long brown hair and wears a blue top with 'ENGINEERING' written on it.",
    image: "https://ext.same-assets.com/994333717/849522504.jpeg",
    metadata: "Metadata Generated by GPT-4o"
  },
  {
    id: 8,
    title: "Basketball Player with Animated Face",
    description: "A cartoon character with an animated face, wearing a black tank top with 'caldera' written on it, is dribbling a basketball labeled 'Rollups' on an outdoor court.",
    image: "https://ext.same-assets.com/1726106507/849522504.jpeg",
    metadata: "Metadata Generated by GPT-4o"
  },
  {
    id: 9,
    title: "Meditative Frog in Tranquil Landscape",
    description: "A cartoon frog is depicted in a meditative pose, sitting cross-legged on a rock. The frog is wearing a dark robe, reminiscent of a monk's attire, and has a serene expression with closed eyes. The background features a vibrant, colorful sky with hues of pink, purple, and orange, suggesting a sunrise or sunset.",
    image: "https://ext.same-assets.com/2559084341/849522504.jpeg",
    metadata: "Metadata Generated by GPT-4o"
  },
  {
    id: 10,
    title: "Pepe the Frog on a Golf Cart",
    description: "A cartoon character resembling Pepe the Frog is driving a golf cart on a golf course. The cart has 'Scaling Ethereum' written on its roof, and the character is wearing a cap with a logo. The background features a golf hole with a flag, a pond, and mountains.",
    image: "https://ext.same-assets.com/2856583683/849522504.jpeg",
    metadata: "Metadata Generated by GPT-4o"
  },
  {
    id: 11,
    title: "Arm Wrestling Showdown",
    description: "A cartoon bear and a muscular frog character arm wrestling in front of a chain-link fence with a cityscape in the background.",
    image: "https://ext.same-assets.com/3343421611/849522504.jpeg",
    metadata: "Metadata Generated by GPT-4o"
  },
  {
    id: 12,
    title: "Festive Frog Santa",
    description: "A cartoon frog dressed as Santa Claus is joyfully holding an orange stocking labeled 'caldera' in front of a decorated Christmas tree, with snow falling in the background.",
    image: "https://ext.same-assets.com/3323210766/849522504.jpeg",
    metadata: "Metadata Generated by GPT-4o"
  },
  {
    id: 13,
    title: "Celebration with Fireworks",
    description: "A cartoon character with an orange face and large eyes, wearing a fur coat and tie, stands in front of a clock tower labeled 'caldera'. Fireworks light up the night sky in the background.",
    image: "https://ext.same-assets.com/490227252/849522504.jpeg",
    metadata: "Metadata Generated by GPT-4o"
  },
  {
    id: 14,
    title: "Chain Reaction",
    description: "A cartoon character with an orange face and large eyes is juggling three circular icons, each with different symbols. The character is wearing a futuristic outfit with a prominent circular emblem on the chest. The background features a glowing red and purple circular frame with the text 'CHAIN REACTION' at the top.",
    image: "https://ext.same-assets.com/3009590519/849522504.jpeg",
    metadata: "Metadata Generated by GPT-4o"
  },
  {
    id: 15,
    title: "Meme Character with Ethereum Symbol",
    description: "A cartoon character with an orange face, wearing a brown fedora and trench coat, holds an Ethereum symbol between their fingers. The background is black, highlighting the character's confident expression and attire.",
    image: "https://ext.same-assets.com/3216107947/849522504.jpeg",
    metadata: "Metadata Generated by GPT-4o"
  },
  {
    id: 16,
    title: "Frog Character Holding Earth",
    description: "A cartoon frog character in a purple jacket is holding a stylized Earth with the word 'caldera' and a logo on it, set against a space background with planets.",
    image: "https://ext.same-assets.com/3424259060/849522504.jpeg",
    metadata: "Metadata Generated by GPT-4o"
  },
  {
    id: 17,
    title: "Warrior in a Fiery Landscape",
    description: "A stylized warrior with a smiling face stands confidently in front of a volcanic landscape. The character wears a black sleeveless top with a triangular emblem, golden armor accents, and holds red sashes in both hands. The background features a volcano with visible lava and a sky filled with clouds and sunlight.",
    image: "https://ext.same-assets.com/992842070/849522504.jpeg",
    metadata: "Metadata Generated by GPT-4o"
  },
  {
    id: 18,
    title: "Swimming Frogman",
    description: "A muscular anthropomorphic frog wearing goggles and a black tank top with 'caldera' written on it, swimming energetically through water with bubbles around.",
    image: "https://ext.same-assets.com/2867096781/849522504.jpeg",
    metadata: "Metadata Generated by GPT-4o"
  },
  {
    id: 19,
    title: "Cartoon Character in Bangkok",
    description: "A cartoon character with an orange face, wearing sunglasses and a hat, is in front of a tuk-tuk labeled 'Caldera'. In the background, there is a golden temple, and a sign for 'DEVCON Southeast Asia' in Bangkok, Thailand, dated 12-15 November.",
    image: "https://ext.same-assets.com/3597913466/849522504.jpeg",
    metadata: "Metadata Generated by GPT-4o"
  },
  {
    id: 20,
    title: "Cartoon Plane Celebrating Independence Day",
    description: "A cartoon character is flying a vintage military-style airplane with a spinning propeller. The character is wearing sunglasses and a scarf, and the plane has an American flag on its side. A red banner trailing behind reads 'America Independence-Day.'",
    image: "https://ext.same-assets.com/3480290031/849522504.jpeg",
    metadata: "Metadata Generated by GPT-4o"
  },
];

export const getArtworkById = (id: number | string): Artwork | undefined => {
  const numId = typeof id === 'string' ? parseInt(id, 10) : id;
  return artworks.find(artwork => artwork.id === numId);
};
